In [59]:
# imports
import pandas as pd
import matplotlib.pyplot as plt

import yfinance as yf
from finvizfinance.quote import finvizfinance

import warnings
warnings.filterwarnings("ignore")

import os

In [60]:
# stocks list
# stocks = [
#     'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'META', 'V', 'NFLX', 'PFE', 'BABA', 'RACE', 'WMT'
# ] # prop firm common tickers

# stocks = [
#     'AAPL', 'NVDA', 'TSLA', 'BLK', 'BX', 'BA', 'C', 'GE', 'GS', 'MU', 'QCOM', 'COIN', 'MARA', 'MSTR', 'PLTR'
# ] # TODO: TRUMP STOCKS

# stocks = [''] # tickers biz + trend insiders

# stocks = ['AMP.MI', 'IGD.MI', 'NEXI.MI', 'REY.MI', 'CPRI.MI'] # # TODO: for the italian tickers, we need to remove market cap filter, they are all small cap

# stocks = [
#     'ACIW', 'ALGN', 'APTV', 'BA', 'CLX', 'CSU', 'CTHS', 'ERIE', 
#     'EXLS', 'FMC', 'GME', 'HOOD', 'HUM', 'JD', 'LVS', 'MSTR', 
#     'NVAX', 'NVO', 'ORCL', 'PDD', 'QCOM', 'TEAM', 'TSCO', 'UAA',
#     'UPS', 'VEEV', 'ZTS', 'CE', 'DUOL', 'FE', 'TRI', 'AQN',
#     'FTK', 'QLYS', 'MOH', 'NOA3.DE', 'ABI', 'CMCSA', 'SUI',
#     'U', 'NICE', 'NXPI', 'ENPH', '1KER.MI', 'PUM.MU', 'TGT',
#     'DXCM', 'WYNN', 'MTD', 'GPC', 'SHOP', 'F', 'RMS', 'OKLO',
#     'SCVL'
# ] # tickers rea style "Trading View"

# stocks = [] 

# stocks = ['GRAB', 'TTD', 'U', 'NOW', 'INTU', 'WDAY', 'DDOG', 'ACN', 'IT','ROKU','FICO','ACN','ADBE','ZS','INTU','SOFI','SAP',
#           'NKE', 'LULU', 'PYPL', 'MC.PA','EEFT','PPC','GCBC','WEX','FAGRO','ADSK','CRM','CRCL','PCTY','C','BKNG','ECMPA','VOC',
#           'VTRS','VEEV','COIN','TRGP','VRSK','WING','SPSC','PTC','MORN','UMI','STM','AOO','ASMB','MOS','MIKK','CPRT','CPNG','FIG',
#           'G24.DE','FLUX','CSTL','RUN','AFX.DE','RIVN','GNRC','BBWI','BLK','ENPH','PLD','O','AMN','BUD','MMS','PSTG','CPS','SE','OVV',
#           'EW','AVAV','OVV','APH','PSTG','VNA.DE','NVAX','FE','DELL','SCVL','PANW','OREP','CARR','AAL','CTSH','SAM','EXLS','ES','QLYS', 
#           'RIVN', 'FTNT', 'TWLO', 'RAMP', 'PODD', 'IDT', 'CDP', 'CBT', 'RDDT', 'BRO', 'SAP', 'NOW', 'TOP', 'MOH', 'TSLX'] # tickers with activated allerts

# stocks = ['ROU','OSI','FRC3','UMI','TNXT','DISW','BRI','STRO','CEBE','VASTB','XCTE','TELEW','SESG','EVS','KENDR','VAN',
#           'LHA','BLUE','OBEL','CEBR','IBC5','COV','ENERW','BYW','BCO','QRF','TITR','MATW','RRTL','PBH','EXAI','MIKO','FMC1',
#           'NEXTA','BIJ','SXR6','HMSB','LYQK','BUND2S','TQI','WEHB','INRG'] 
# # tickers from poc scanner EU

stocks = [
            'OCFC', 'XOMA', 'KALV', 'RIOT', 'OMER', 'SNDX', 'ASRT',
            'ZVRA', 'ANGO', 'SBLK', 'TITN', 'WSBC', 'ZVRA', 'ASRT',
            'ENTA', 'BUSE', 'COLB', 'TSSI', 'MCFT', 'LCNB', 'VC',
            'STRS', 'PROV', 'CIVB', 'RGS', 'MTRX', 'DRH', 'ATNI',
            'CFBK', 'SHBI', 'ISSC', 'TACO', 'NFBK', 'DGICB', 'FFIC',
            'ALCO', 'HAFC', 'BJRI', 'FIBK', 'SHEN', 'VLY', 'LIVN', 
            'ZUMZ','RUN', 'ALKS', 'VTRS', 'SSBI', 'POET', 'QRVO', 'HCSG',
            'WTBA', 'MVBF', 'INVA', 'CSIQ', 'MATW', 'OSBC', 'DUOT',
            'APA', 'ASTE', 'ATLO', 'ADTN', 'BMRC', 'PLSE', 'TWIN', 
            'CLSK', 'CLDX', 'QURE', 'VCYT', 'CVBF', 'IPGP', 'FUSB',
            'CTRN', 'ATRA', 'AUPH', 'PAGP', 'GLRE', 'GLNG', 'ALGT', 'FSTR', 'NTGR',
            'GLRE', 'GLNG', 'ALGT', 'FSTR', 'NTGR', 'CYRX', 'WBD', 'DAKT', 'ASYS', 'JOUT',
            'CRVS', 'LBTYA', 'SILC', 'AMRX', 'CMPR', 'SIFY', 'VECO', 'HAS', 'OCC',
            'RCKY', 'NKTR', 'CORT', 'WRLD', 'TSAT', 'AXGN',
            'ILMN', 'LPTH', 'BIIB', 'MTCH', 'TIGO', 'LQDT',
            'BPOP', 'SSRM', 'ESEA', 'SEDG', 'WULF', 'TATT',
            'APLD', 'EXTR', 'AMSC', 'ACLS', 'CHCI', 'SYNA', 'CLMT', 'LWLG', 'CYTK', 'UTMD',
            'INTG', 'MAYS', 'CGNX', 'DLTR', 'INCY', 'HIFS', 'XPEL', 'MHK', 'PATH',
            'APP', 'SAPG', 'IBM', 'OBEL', 'PUMG', 'EZJ', 
            'MQ', 'PGR', 'ACN', 'GDD', 'IVZ', 'INTU', 'SST',
            'SAM', 'DOCU', 'ROL', 'CBRL', 'WLK', 'DASH', 'EL.PA', 'CRM', 
            'ACN', 'ADSK', 'MSFT', 'CSU', 'RBLK', 'ABNB', 'BAC', 'HPQ',
            'PDD', 'MDB', 'FTNT', 'UEN.F', 'PLTR', 'UBER', 'P911.DE', 'KER',
            'GRAB', 'FMC', 'LUNR', 'ADBE', 'SG', 'TSCO', 'SBLK', 'FLG', 'BSX',
            'RI', 'AFX', 'F', 'KHC', 'GDYN', 'FR', '7974.T', 'FTK', 'DDD',
            'WDAY', 'PAYC', 'HUBS', 'PERI', 'DUOL', 'DUOT', 'MGM', 'CDP',
            'APPS', 'NVAX', 'GPN', 'BJRI', 'STAA', 'AFX.DE', 'SBLK', 'STAA', 'COIN',
            'ABBV', 'VTRS', 'DOCU', 'CARR', 'J', 'AMN', 'LMT', 'FCEL',
            'PODD', 'ECOR', 'DPKO', 'FMC', 'WKL', 'KALV', 'NVO', 'TSCO', 'CSIQ',
            'EBS', 'SRPT', 'APA', 'NU', '0700.HQ', 'EFOR', 'CAT', 'BE', 'KEEL', 'MCD', 'WIX', 'HIMS', 'BAC',
            'FICO', 'ACN', 'AMP.MI', 'ADBE', 'IGD.MI', 'ECOR',
            'BMI', 'NEXI.MI', 'BB', 'SMR', 'UBI.PA', 'ZS',
            'SOUN', 'AMSC', 'AFX', 'INTU', 'SOFI', 'TTWO', 'BAS', 
            'LYFT', 'BBW', 'TEP', 'REY.MI', 'RNG', 'WING',
            'FIGMA', 'TSM', 'NVO', 'DUOL', 'PLTR', 'ORCL', 'AVGO',
            'AMD', 'APP', 'NVDA', 'ANET', 'CRWD', 'STX', 'WDC',
            'NKE', 'PEP', 'CCL', 'GRAB', 'STLA', 'NCLH', 'VICI', 'AS', 'TMUS', 'TME', 'LEN', 'LVS', 'FIS', 'BROS',
            'EXC', 'TU', 'ROL', 'IONS', 'BLDR', 'AMZR', 'CLX', 'SARO', 'CMS', 'WYNN', 'PEG',
            'EPRT', 'TTAN', 'LOW', 'YUM', 'NRG', 'GLPU', 'STZ',
            'AON', 'PNR', 'RTO', 'SFD', 'WH', 'AN', 'ADC', 'VMC', 'SPCX',
            'RDDT', 'AXP', 'STM', 'WMT', 'AVGO', 'SOFI', 'DKNG',
            'SHAK', 'GME', 'KR', 'CRDO', 'CRCL', 'VST',
            'BMNR', 'COHR', 'AST', 'UBER', 'CRWV', 'NET', 'QCOM', 'COIN', 'SHW', 'BABA', 'CAT', 'RTX',
            'RKLB', 'ORLY', 'AZO', 'CASY', 'ROST', 'CHD', 'TSCO', 'SHW', 'BALL', 'ROL', 
            'IEX', 'AAON', 'AAPL', 'RMS', 'APH', 'DHR', 'MTD',
            'WDC', 'DECK', 'ULTA', 'SNDA', 'XYZ',
            'GRAB', 'TTD', 'U', 'NOW', 'INTU', 'WDAY', 'DDOG', 'ACN', 'IT','ROKU','FICO','ACN','ADBE','ZS','INTU','SOFI','SAP',
            'NKE', 'LULU', 'PYPL', 'MC.PA','EEFT','PPC','GCBC','WEX','FAGRO','ADSK','CRM','CRCL','PCTY','C','BKNG','ECMPA','VOC',
            'VTRS','VEEV','COIN','TRGP','VRSK','WING','SPSC','PTC','MORN','UMI','STM','AOO','ASMB','MOS','MIKK','CPRT','CPNG','FIG',
            'G24.DE','FLUX','CSTL','RUN','AFX.DE','RIVN','GNRC','BBWI','BLK','ENPH','PLD','O','AMN','BUD','MMS','PSTG','CPS','SE','OVV',
            'EW','AVAV','OVV','APH','PSTG','VNA.DE','NVAX','FE','DELL','SCVL','PANW','OREP','CARR','AAL','CTSH','SAM','EXLS','ES','QLYS', 
            'RIVN', 'FTNT', 'TWLO', 'RAMP', 'PODD', 'IDT', 'CDP', 'CBT', 'RDDT', 'BRO', 'SAP', 'NOW', 'TOP', 'MOH', 'TSLX'
            'RGTI', 'APP', 'MELI', 'OKLO', 'PL', 'ONDS', 'NFLX', 'KTOS', 'BA', 'LMT',
            'DVN', 'SWK', 'XYZ', 'AES', 'VTRS', 'PFE', 'APA', 'BIIB', 'EL',
            'ILMN',            
            ]
# tickers rea style "TUTTE"

# stocks = [
#     'ORLY', 'AZO', 'CASY', 'ROST', 'CHD', 'TSCO', 'SHW', 'BALL', 'ROL', 
#     'IEX', 'AAON', 'AAPL', 'RMS', 'APH', 'DHR', 'MTD'] # tickers coma style

# # # saved stocks tickers are int the directory "../14_stocks_analysis\asset". They are saved as .png files, with the ticker as filename (e.g. AAPL.png). 
# # # # The stocks list below use the filenames (without .png extension) from the "../14_stocks_analysis\asset" directory, to create the list of tickers to analyze.
# stocks_dir = r"..\14_stocks_analysis\asset"
# stocks = [os.path.splitext(filename)[0] for filename in os.listdir(stocks_dir) if filename.lower().endswith(('.jpg', '.jpeg', '.png'))]

# stocks list can have duplicates, we remove them in the following line
stocks = list(set(stocks))

# source directories toggle
use_rankings_main = False          # ..\14_stocks_analysis\00_rankings
use_rankings_sector = True        # ..\14_stocks_analysis\01_rankings_sector
use_stocks_list = True             # manually entered tickers in 'stocks' list above
# set both use_rankings_* and use_stocks_list = True for combined mode

dir_options = [
    (use_rankings_main, r"..\14_stocks_analysis\00_rankings"),
    (use_rankings_sector, r"..\14_stocks_analysis\01_rankings_sector"),
]
selected_dirs = [path for enabled, path in dir_options if enabled]

if not selected_dirs and not use_stocks_list:
    raise ValueError('Enable at least one source directory or set use_stocks_list = True in Cell 2.')

if selected_dirs:
    missing_dirs = [path for path in selected_dirs if not os.path.isdir(path)]
    if missing_dirs:
        raise FileNotFoundError(f'Directories do not exist: {missing_dirs}')

if use_stocks_list and selected_dirs:
    print('Combined mode: rankings + stocks list')
    for path in selected_dirs:
        print(f' - {path}')
    print('Stocks list:', stocks)
elif use_stocks_list:
    print('Using stocks list:', stocks)
else:
    print('Using data directories:')
    for path in selected_dirs:
        print(f' - {path}')

Combined mode: rankings + stocks list
 - ..\14_stocks_analysis\01_rankings_sector
Stocks list: ['AMN', 'SEDG', 'WSBC', 'KEEL', 'DASH', 'DDOG', 'CSU', 'SAPG', 'CHD', 'PERI', 'ATRA', 'OBEL', 'NTGR', 'IDT', 'TATT', 'LVS', 'STLA', 'BMRC', 'EXC', 'AXP', 'FFIC', 'VICI', 'POET', 'CYRX', 'GRAB', 'STX', 'ES', 'ADTN', 'FAGRO', 'LPTH', 'MIKK', 'GDYN', 'EL.PA', 'IVZ', 'FMC', 'VLY', 'ECOR', 'DLTR', 'AES', 'PAYC', 'BAS', 'EFOR', 'NFBK', 'SAP', 'LULU', 'MAYS', 'RI', 'MOH', 'BBWI', 'LEN', 'EXLS', 'ORLY', 'HIFS', 'CMS', 'C', 'BKNG', 'INTU', 'OSBC', 'BMNR', 'CPS', 'PODD', 'TSCO', 'CRWD', 'RUN', 'CGNX', 'TSM', 'TMUS', 'RCKY', 'APH', 'SIFY', 'GLPU', 'RTX', 'PAGP', 'NKTR', 'UEN.F', 'COLB', 'SST', 'MTCH', 'CHCI', 'DDD', 'CLSK', 'DECK', 'SMR', 'DELL', 'RGS', 'TSAT', 'DAKT', 'PUMG', 'PROV', 'WULF', 'BA', 'ADC', 'IGD.MI', 'CSIQ', 'INCY', 'MCFT', 'RBLK', 'PLTR', 'CMPR', 'CVBF', 'COIN', 'ABBV', 'XYZ', 'UTMD', 'WIX', 'MOS', 'SYNA', 'EW', 'ALGT', 'WEX', 'PLD', 'LUNR', 'AXGN', 'NVAX', 'DUOT', 'LMT', 'IONS', 'DHR', 'PCTY', 'OREP', 'NOW', 'TSLXRGTI', 'ANGO', 'AVAV', 'HUBS', 'J', 'SE', 'FUSB', 'AAPL', 'KR', 'SG', 'ORCL', 'RIVN', '0700.HQ', 'ABNB', 'CSTL', 'MGM', 'DKNG', 'UBER', 'VEEV', 'GNRC', 'MMS', 'ISSC', 'FLUX', 'VECO', 'SBLK', 'SSBI', 'ENPH', 'CASY', 'WING', 'WYNN', 'TWIN', 'FE', 'PL', 'AN', 'BBW', 'MTRX', 'AUPH', 'WDAY', 'MDB', 'AVGO', 'ASRT', 'BUSE', 'BJRI', 'CYTK', 'CTSH', 'TME', 'MTD', 'ADSK', 'VCYT', 'AOO', 'AMSC', 'AMP.MI', 'ASYS', 'HCSG', 'HAFC', 'CARR', 'FIGMA', 'ESEA', 'LYFT', 'BSX', 'RKLB', 'CPRT', 'CRWV', 'TTD', 'RTO', 'TACO', 'STRS', 'VNA.DE', 'PDD', 'U', 'SFD', 'SWK', 'SPSC', 'MORN', 'OCFC', 'EXTR', 'APPS', 'XOMA', 'MELI', 'SOUN', 'WMT', 'BPOP', 'LIVN', 'GLNG', 'VC', 'BE', 'VTRS', 'PSTG', 'TITN', 'TWLO', 'NEXI.MI', 'REY.MI', 'INVA', 'OKLO', 'SHAK', 'SHW', 'FCEL', 'F', 'BROS', 'CLMT', 'VOC', 'IBM', 'GLRE', 'AMD', 'CLX', 'MQ', 'LQDT', 'CRM', 'FTK', 'MCD', 'OVV', 'VST', 'PPC', 'FIG', 'ALCO', 'WLK', 'ADBE', 'PFE', 'MATW', 'AZO', 'GCBC', 'QRVO', 'EBS', 'SHBI', 'PTC', 'ANET', 'ECMPA', 'TSSI', 'RIOT', 'PNR', 'ASTE', 'WRLD', 'SSRM', 'QCOM', 'ASMB', 'MHK', 'EPRT', 'TRGP', 'ACN', 'ALKS', 'RMS', 'KTOS', 'YUM', 'LWLG', 'ZS', 'LBTYA', 'PATH', 'COHR', 'NFLX', 'SHEN', 'FSTR', 'SNDA', 'FICO', 'BUD', 'SILC', 'AMRX', 'EL', 'SAM', 'NKE', 'NRG', 'CCL', 'NVDA', 'CIVB', 'CDP', 'BLDR', 'NU', 'WKL', 'AS', 'BALL', 'RAMP', 'BMI', 'APA', 'STZ', 'TOP', 'APP', 'KER', 'ATLO', 'CRCL', 'BRO', 'CLDX', 'CPNG', 'SRPT', 'STAA', 'RDDT', 'HIMS', 'ULTA', 'EEFT', 'AAL', 'IPGP', 'O', 'SOFI', 'WH', 'KALV', 'FIS', 'NVO', 'AAON', 'APLD', 'JOUT', 'DOCU', 'LOW', 'SNDX', 'PEG', 'ZVRA', 'RNG', 'CBT', 'BIIB', 'STM', 'GME', 'IEX', 'NCLH', 'PLSE', '7974.T', 'CBRL', 'G24.DE', 'HPQ', 'P911.DE', 'AMZR', 'TTAN', 'TTWO', 'ZUMZ', 'BB', 'ENTA', 'DGICB', 'BAC', 'KHC', 'HAS', 'INTG', 'BLK', 'CRDO', 'ROKU', 'ACLS', 'FLG', 'PYPL', 'LCNB', 'PEP', 'UBI.PA', 'UMI', 'TEP', 'SARO', 'WTBA', 'QURE', 'GDD', 'VMC', 'AST', 'OMER', 'CRVS', 'ROST', 'CFBK', 'MSFT', 'AFX', 'MC.PA', 'DVN', 'BABA', 'ONDS', 'IT', 'WBD', 'SCVL', 'CTRN', 'OCC', 'AON', 'XPEL', 'VRSK', 'FIBK', 'QLYS', 'WDC', 'MVBF', 'DRH', 'PANW', 'CORT', 'FR', 'TU', 'GPN', 'FTNT', 'ROL', 'AFX.DE', 'ILMN', 'ATNI', 'DPKO', 'TIGO', 'CAT', 'DUOL', 'NET', 'PGR', 'SPCX', 'EZJ']

In [61]:
if selected_dirs:
    # rankings mode (or combined): load from files
    # in combined mode, manual stocks are appended after ranking-specific processing
    files = []

    for dir_path in selected_dirs:
        dir_files = [
            file for file in os.listdir(dir_path)
            if file.lower().endswith(('.csv', '.xlsx', '.xls'))
        ]
        files.extend([(dir_path, file) for file in dir_files])

    if not files:
        raise ValueError(f'No CSV/XLSX/XLS files found in selected directories: {selected_dirs}')

    def load_table(dir_path, file_name):
        file_path = os.path.join(dir_path, file_name)
        if file_name.lower().endswith('.csv'):
            return pd.read_csv(file_path)
        return pd.read_excel(file_path)

    # file name format like 2603, 2602... first two digits year, last two month
    def extract_date(file_name):
        year = int(file_name[:2]) + 2000
        month = int(file_name[2:4])
        return pd.Timestamp(year=year, month=month, day=1)

    df = pd.concat(
        [
            load_table(dir_path, file_name).assign(
                date=extract_date(file_name),
                source_dir=os.path.basename(dir_path),
            )
            for dir_path, file_name in sorted(files, key=lambda x: (x[0], x[1]))
        ],
        ignore_index=True,
    )

    # lowercase column names
    df.columns = df.columns.str.lower()

    # replace spaces with underscore in column names
    df.columns = df.columns.str.replace(' ', '_')

    df.head()

else:
    # pure stocks list mode: build df directly from the manually entered stocks list
    df = pd.DataFrame({'symbol': stocks})
    df.head()

In [62]:
# print len of dataframe
print(f"Dataframe length: {len(df)}")

Dataframe length: 300

In [63]:
if selected_dirs:
    # create a copy of symbol column named 'symbol_copy'
    df['symbol_copy'] = df['symbol']

In [64]:
if selected_dirs:
    # the series in df.symbol_copy, should be shifted backwards by 1 row, to align with the stock name in the same row
    df['symbol_copy'] = df['symbol_copy'].shift(-1)

In [65]:
if selected_dirs:
    # drop nan in df.unnamed:_0
    df = df.dropna(subset=['unnamed:_0'])

In [66]:
if selected_dirs:
    # drop columns 'unnamed: 0', 'symbol' (ignore if already removed)
    df = df.drop(columns=['unnamed:_0', 'symbol'], errors='ignore')

    # rename column 'symbol_copy' to 'symbol' if needed
    if 'symbol_copy' in df.columns and 'symbol' not in df.columns:
        df = df.rename(columns={'symbol_copy': 'symbol'})

    # columns order
    selected_cols = [
        'date', 'symbol', 'stock', 'market_cap', 'price',
        'fair_value_(%)', 'z-score', 'f-score', 'm-score', 'value_generation'
    ]

    # if 'price' is missing, continue without it
    if 'price' not in df.columns:
        selected_cols = [c for c in selected_cols if c != 'price']

    # keep only columns that exist
    selected_cols = [c for c in selected_cols if c in df.columns]
    df = df[selected_cols]

In [67]:
df.columns

Index(['date', 'symbol', 'stock', 'market_cap', 'fair_value_(%)', 'z-score',
       'f-score', 'm-score', 'value_generation'],
      dtype='object')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 298
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              150 non-null    datetime64[us]
 1   symbol            150 non-null    object
 2   stock             150 non-null    object
 3   market_cap        150 non-null    object
 4   fair_value_(%)    150 non-null    object
 5   z-score           150 non-null    float64
 6   f-score           150 non-null    float64
 7   m-score           150 non-null    float64
 8   value_generation  150 non-null    object
dtypes: datetime64[us](1), float64(3), object(5)
memory usage: 11.7+ KB

In [69]:
if selected_dirs:
    # create a copy of the dataframe
    df_copy = df.copy()

    # keep only date, symbol columns
    df_copy = df_copy[['date', 'symbol']]

    # group by symbol and count the number of occurrences of each symbol
    symbol_counts = df_copy.groupby('symbol').size().reset_index(name='count')

    # sort the dataframe by count in descending order
    symbol_counts = symbol_counts.sort_values(by='count', ascending=False)

    # display the top 10 symbols with the most occurrences
    print(symbol_counts.head(10))

       symbol  count
0     0700.HK      1
94       NATH      1
96       NFLX      1
97       NLOP      1
98       NMRK      1
99       NRDS      1
100      NREF      1
101       NSA      1
102  NWSLV.AX      1
103      NXDR      1

In [70]:
if selected_dirs:
    # drop duplicates in df.symbol, keep last occurrence
    df = df.drop_duplicates(subset='symbol', keep='last')

    # merge df with symbol_counts on symbol, keeping only rows that are in df
    df = df.merge(symbol_counts, on='symbol', how='inner')

    # sort df by count in descending order
    df = df.sort_values(by='count', ascending=False)

    display(df.head(10))

,date,symbol,stock,market_cap,fair_value_(%),z-score,f-score,m-score,value_generation,count
0,2026-10-01,FLXS,"Flexsteel Industries, Inc.",378.21M,+2.88,5.86,8.0,-3.01,Robust,1
94,2026-10-01,4071.SR,Arabian Contracting Services Company,584.69M,+39.35,0.74,4.0,-3.95,Steady,1
96,2026-10-01,GLIBA,Liberty Capital Corporation,818.00M,+115.40,0.13,3.0,-2.96,Steady,1
97,2026-10-01,TBLA,Taboola.com Ltd.,956.87M,+99.13,2.74,8.0,-2.68,Steady,1
98,2026-10-01,1024.HK,Kuaishou Technology,16.10B,+91.84,0.40,3.0,-2.56,Resilient,1
99,2026-10-01,AAF.L,Airtel Africa Plc,13.85B,+45.38,10.49,8.0,-2.59,Steady,1
100,2026-10-01,SCG.AX,Scentre Group,12.44B,+120.41,1.36,7.0,-3.27,Robust,1
101,2026-10-01,NMRK,"Newmark Group, Inc.",2.14B,+84.65,1.75,6.0,-3.32,Robust,1
102,2026-10-01,WALL-B.ST,Wallenstam AB (publ),2.36B,+80.81,0.57,6.0,-3.38,Robust,1
103,2026-10-01,4324.SR,Banan Real Estate Co.,155.29M,+85.62,2.80,8.0,-2.93,Resilient,1

In [71]:
if selected_dirs:
    # market cap column is object. We need to convert it to numeric, removing any non-numeric characters
    # ("T" indicating trillions, "B" indicating billions, "M" indicating millions, "K" indicating thousands)

    # take last character of market cap column and add a new column 'market_cap_um'
    df['market_cap_um'] = df['market_cap'].str[-1]

    # replace 'T', 'B', 'M', 'K' with "" in market cap column and convert to numeric
    df['market_cap'] = df['market_cap'].str.replace(r'[TBMK]', '', regex=True).astype(float)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 149
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              150 non-null    datetime64[us]
 1   symbol            150 non-null    object
 2   stock             150 non-null    object
 3   market_cap        150 non-null    float64
 4   fair_value_(%)    150 non-null    object
 5   z-score           150 non-null    float64
 6   f-score           150 non-null    float64
 7   m-score           150 non-null    float64
 8   value_generation  150 non-null    object
 9   count             150 non-null    int64
 10  market_cap_um     150 non-null    object
dtypes: datetime64[us](1), float64(4), int64(1), object(5)
memory usage: 14.1+ KB

In [73]:
if selected_dirs:
    # if market cap um is M, market cap / 1000, if market cap um is T, market cap * 1000, if market cap um is B, market cap / 1
    def convert_market_cap(row):
        if row['market_cap_um'] == 'M':
            return row['market_cap'] / 1000
        elif row['market_cap_um'] == 'T':
            return row['market_cap'] * 1000
        elif row['market_cap_um'] == 'B':
            return row['market_cap']
        elif row['market_cap_um'] == 'K':
            return row['market_cap'] / 1000
        else:
            return row['market_cap']

    # apply the function to the dataframe and create a new column 'market_cap_converted'
    df['market_cap_converted'] = df.apply(convert_market_cap, axis=1)

In [74]:
if selected_dirs:
    # drop market cap	
    df = df.drop(columns=['market_cap'])

    # rename market cap converted to market cap
    df = df.rename(columns={'market_cap_converted': 'market_cap'})

    # columns order 'date', 'symbol', 'stock', 'price', 'fair value (%)', 'z-score', 'f-score', 'm-score', 'value generation', 'market cap um', 'market cap'
    desired_cols = ['date', 'symbol', 'stock', 'price', 'fair_value_(%)', 'z-score',
    'f-score', 'm-score', 'value_generation', 'market_cap_um', 'market_cap', 'count']
    df = df[[c for c in desired_cols if c in df.columns]]

In [75]:
if selected_dirs:
    # --- market cap filter ---
    # drop all rows where market cap um is M and K
    df = df[~df['market_cap_um'].isin(['M', 'K'])]

    # drop all rows where market cap um is B and market cap is less than 10
    df = df[~((df['market_cap_um'] == 'B') & (df['market_cap'] < 10))]

    # rename df.market_cap to market_cap_(B)
    df = df.rename(columns={'market_cap': 'market_cap_(B)'})

    # drop market_cap_um
    df = df.drop(columns=['market_cap_um'])

In [76]:
# add currency column according to the stock exchange where the stock is listed. Need to identify currency based on df.symbol 
# ends with:
# .MI -> EUR
# .MC -> EUR
# .DE -> EUR
# .PA -> EUR
# .L -> GBP
# .T -> JPY
# .AX -> AUD
# .SR -> SAR
# .HK -> HKD
# .TO -> CAD
# .NZ -> NZD
# .KL -> MYR
# .MX -> MXN
# if df.symbol does not contain ".", add USD as currency
# if none of the above conditions are met, currency 
def identify_currency(symbol):
    if symbol.endswith('.MI') or symbol.endswith('.DE') or symbol.endswith('.PA') or symbol.endswith('.SW'):
        return 'EUR'
    elif symbol.endswith('.L'):
        return 'GBP'
    elif symbol.endswith('.T'):
        return 'JPY'
    elif symbol.endswith('.AX'):
        return 'AUD'
    elif symbol.endswith('.SR'):
        return 'SAR'
    elif symbol.endswith('.HK'):
        return 'HKD'
    elif symbol.endswith('.TO'):
        return 'CAD'
    elif symbol.endswith('.NZ'):
        return 'NZD'
    elif symbol.endswith('.KL'):
        return 'MYR'
    elif symbol.endswith('.MX'):
        return 'MXN'
    elif '.' not in symbol:
        return 'USD'
    else:
        return 'Unknown'
    
# apply the function to the dataframe and create a new column 'currency'
df['currency'] = df['symbol'].apply(identify_currency)

In [77]:
# print Unknown symbols in currency column
print(df[df['currency'] == 'Unknown']['symbol'])

81     YDEX.ME
83      KPN.AS
84    TELIA.ST
60      REN.AS
Name: symbol, dtype: object

In [78]:
# --- currency filter ---
# keep only EUR and USD stocks
df = df[df['currency'].isin(['EUR', 'USD'])]

In [79]:
if selected_dirs:
    # --- solidity filter ---
    # convert z-score, f-score, m-score to numeric
    df['z-score'] = pd.to_numeric(df['z-score'], errors='coerce')
    df['f-score'] = pd.to_numeric(df['f-score'], errors='coerce')
    df['m-score'] = pd.to_numeric(df['m-score'], errors='coerce')

    # drop all rows where z-score is less than 1.81
    # drop all rows where f-score is less than 3
    # drop all rows where m-score is higher than -1.78
    df = df[~((df['z-score'] < 1.81) | (df['f-score'] < 3) | (df['m-score'] > -1.78))]

In [80]:
if selected_dirs:
    # --- fair_value_(%) filter ---
    # convert fair_value_(%) to numeric
    df['fair_value_(%)'] = pd.to_numeric(df['fair_value_(%)'], errors='coerce')

    # keep only rows where fair_value_(%) is higher than 0
    df = df[df['fair_value_(%)'] > 0]

In [81]:
# combined mode: append manually entered stocks to the rankings-filtered df
# (ranking-specific filters above already ran; manual stocks bypass them intentionally)
if use_stocks_list and selected_dirs:
    existing = set(df['symbol'].values)
    extra = pd.DataFrame({'symbol': [s for s in stocks if s not in existing]})
    df = pd.concat([df, extra], ignore_index=True)
    print(f'Combined mode: {len(df)} total rows ({len(extra)} manual stock(s) appended)')

Combined mode: 410 total rows (405 manual stock(s) appended)

In [82]:
# list of tickers in the dataframe
tickers = df['symbol'].tolist()

In [83]:
tickers

['HST',
 'NFLX',
 'FOX',
 'FOXA',
 'MUSA',
 'AMN',
 'SEDG',
 'WSBC',
 'KEEL',
 'DASH',
 'DDOG',
 'CSU',
 'SAPG',
 'CHD',
 'PERI',
 'ATRA',
 'OBEL',
 'NTGR',
 'IDT',
 'TATT',
 'LVS',
 'STLA',
 'BMRC',
 'EXC',
 'AXP',
 'FFIC',
 'VICI',
 'POET',
 'CYRX',
 'GRAB',
 'STX',
 'ES',
 'ADTN',
 'FAGRO',
 'LPTH',
 'MIKK',
 'GDYN',
 'EL.PA',
 'IVZ',
 'FMC',
 'VLY',
 'ECOR',
 'DLTR',
 'AES',
 'PAYC',
 'BAS',
 'EFOR',
 'NFBK',
 'SAP',
 'LULU',
 'MAYS',
 'RI',
 'MOH',
 'BBWI',
 'LEN',
 'EXLS',
 'ORLY',
 'HIFS',
 'CMS',
 'C',
 'BKNG',
 'INTU',
 'OSBC',
 'BMNR',
 'CPS',
 'PODD',
 'TSCO',
 'CRWD',
 'RUN',
 'CGNX',
 'TSM',
 'TMUS',
 'RCKY',
 'APH',
 'SIFY',
 'GLPU',
 'RTX',
 'PAGP',
 'NKTR',
 'UEN.F',
 'COLB',
 'SST',
 'MTCH',
 'CHCI',
 'DDD',
 'CLSK',
 'DECK',
 'SMR',
 'DELL',
 'RGS',
 'TSAT',
 'DAKT',
 'PUMG',
 'PROV',
 'WULF',
 'BA',
 'ADC',
 'IGD.MI',
 'CSIQ',
 'INCY',
 'MCFT',
 'RBLK',
 'PLTR',
 'CMPR',
 'CVBF',
 'COIN',
 'ABBV',
 'XYZ',
 'UTMD',
 'WIX',
 'MOS',
 'SYNA',
 'EW',
 'ALGT',
 'WEX',
 'PLD',
 'LUNR',
 'AXGN',
 'NVAX',
 'DUOT',
 'LMT',
 'IONS',
 'DHR',
 'PCTY',
 'OREP',
 'NOW',
 'TSLXRGTI',
 'ANGO',
 'AVAV',
 'HUBS',
 'J',
 'SE',
 'FUSB',
 'AAPL',
 'KR',
 'SG',
 'ORCL',
 'RIVN',
 '0700.HQ',
 'ABNB',
 'CSTL',
 'MGM',
 'DKNG',
 'UBER',
 'VEEV',
 'GNRC',
 'MMS',
 'ISSC',
 'FLUX',
 'VECO',
 'SBLK',
 'SSBI',
 'ENPH',
 'CASY',
 'WING',
 'WYNN',
 'TWIN',
 'FE',
 'PL',
 'AN',
 'BBW',
 'MTRX',
 'AUPH',
 'WDAY',
 'MDB',
 'AVGO',
 'ASRT',
 'BUSE',
 'BJRI',
 'CYTK',
 'CTSH',
 'TME',
 'MTD',
 'ADSK',
 'VCYT',
 'AOO',
 'AMSC',
 'AMP.MI',
 'ASYS',
 'HCSG',
 'HAFC',
 'CARR',
 'FIGMA',
 'ESEA',
 'LYFT',
 'BSX',
 'RKLB',
 'CPRT',
 'CRWV',
 'TTD',
 'RTO',
 'TACO',
 'STRS',
 'VNA.DE',
 'PDD',
 'U',
 'SFD',
 'SWK',
 'SPSC',
 'MORN',
 'OCFC',
 'EXTR',
 'APPS',
 'XOMA',
 'MELI',
 'SOUN',
 'WMT',
 'BPOP',
 'LIVN',
 'GLNG',
 'VC',
 'BE',
 'VTRS',
 'PSTG',
 'TITN',
 'TWLO',
 'NEXI.MI',
 'REY.MI',
 'INVA',
 'OKLO',
 'SHAK',
 'SHW',
 'FCEL',
 'F',
 'BROS',
 'CLMT',
 'VOC',
 'IBM',
 'GLRE',
 'AMD',
 'CLX',
 'MQ',
 'LQDT',
 'CRM',
 'FTK',
 'MCD',
 'OVV',
 'VST',
 'PPC',
 'FIG',
 'ALCO',
 'WLK',
 'ADBE',
 'PFE',
 'MATW',
 'AZO',
 'GCBC',
 'QRVO',
 'EBS',
 'SHBI',
 'PTC',
 'ANET',
 'ECMPA',
 'TSSI',
 'RIOT',
 'PNR',
 'ASTE',
 'WRLD',
 'SSRM',
 'QCOM',
 'ASMB',
 'MHK',
 'EPRT',
 'TRGP',
 'ACN',
 'ALKS',
 'RMS',
 'KTOS',
 'YUM',
 'LWLG',
 'ZS',
 'LBTYA',
 'PATH',
 'COHR',
 'SHEN',
 'FSTR',
 'SNDA',
 'FICO',
 'BUD',
 'SILC',
 'AMRX',
 'EL',
 'SAM',
 'NKE',
 'NRG',
 'CCL',
 'NVDA',
 'CIVB',
 'CDP',
 'BLDR',
 'NU',
 'WKL',
 'AS',
 'BALL',
 'RAMP',
 'BMI',
 'APA',
 'STZ',
 'TOP',
 'APP',
 'KER',
 'ATLO',
 'CRCL',
 'BRO',
 'CLDX',
 'CPNG',
 'SRPT',
 'STAA',
 'RDDT',
 'HIMS',
 'ULTA',
 'EEFT',
 'AAL',
 'IPGP',
 'O',
 'SOFI',
 'WH',
 'KALV',
 'FIS',
 'NVO',
 'AAON',
 'APLD',
 'JOUT',
 'DOCU',
 'LOW',
 'SNDX',
 'PEG',
 'ZVRA',
 'RNG',
 'CBT',
 'BIIB',
 'STM',
 'GME',
 'IEX',
 'NCLH',
 'PLSE',
 '7974.T',
 'CBRL',
 'G24.DE',
 'HPQ',
 'P911.DE',
 'AMZR',
 'TTAN',
 'TTWO',
 'ZUMZ',
 'BB',
 'ENTA',
 'DGICB',
 'BAC',
 'KHC',
 'HAS',
 'INTG',
 'BLK',
 'CRDO',
 'ROKU',
 'ACLS',
 'FLG',
 'PYPL',
 'LCNB',
 'PEP',
 'UBI.PA',
 'UMI',
 'TEP',
 'SARO',
 'WTBA',
 'QURE',
 'GDD',
 'VMC',
 'AST',
 'OMER',
 'CRVS',
 'ROST',
 'CFBK',
 'MSFT',
 'AFX',
 'MC.PA',
 'DVN',
 'BABA',
 'ONDS',
 'IT',
 'WBD',
 'SCVL',
 'CTRN',
 'OCC',
 'AON',
 'XPEL',
 'VRSK',
 'FIBK',
 'QLYS',
 'WDC',
 'MVBF',
 'DRH',
 'PANW',
 'CORT',
 'FR',
 'TU',
 'GPN',
 'FTNT',
 'ROL',
 'AFX.DE',
 'ILMN',
 'ATNI',
 'DPKO',
 'TIGO',
 'CAT',
 'DUOL',
 'NET',
 'PGR',
 'SPCX',
 'EZJ']

In [84]:
# TODO: when we have new data, below code can be used to update the fundamentals cache, 
# by downloading fundamentals for all tickers in the dataframe, 
# keeping only the keys in keys_to_keep, prefixing the columns with "fv_", 
# and writing the cache to a CSV file. This way we can keep the fundamentals cache 
# updated with the latest tickers in the dataframe, 
# without having to download fundamentals for all tickers every time we run the notebook.

# batch fundamentals download for all tickers (keeps only keys_to_keep, prefixes columns, writes cache CSV)
from pathlib import Path
import re
import time
import requests
from bs4 import BeautifulSoup

keys_to_keep = ['Company', 'Sector', 'Industry', 'P/E', 'EPS (ttm)',
'Perf Week', 'Market Cap','Forward P/E', 'Perf Month',
'Short Float', 'Perf Quarter', 'P/S', 'EPS this Y',
'Short Ratio', 'Perf Half Y', 'P/B', 'ROA', 'Perf YTD', 'P/C',
'ROE', '52W High', 'Perf Year', 'P/FCF', 'EPS past 3/5Y', 'ROIC', '52W Low', 'Perf 3Y', 'Dividend Est.',
'EV/EBITDA', 'Sales past 3/5Y', 'Volatility W', 'Volatility M', 'Perf 5Y', 'Dividend TTM', 'EV/Sales', 'EPS Y/Y TTM',
'Oper. Margin', 'ATR (14)', 'Perf 10Y', 'Quick Ratio', 'Sales Y/Y TTM', 'Profit Margin', 'RSI (14)', 'Recom',
'Dividend Gr. 3/5Y', 'Current Ratio', 'EPS Q/Q', 'SMA20', 'Beta', 'Payout', 'Debt/Eq', 'Sales Q/Q', 'SMA50', 'Rel Volume',
'Prev Close', 'LT Debt/Eq', 'SMA200', 'Avg Volume', 'Price', 'IPO', 'EPS/Sales Surpr.', 'Trades', 'Volume', 'Change']

def normalize_fundament_key(key):
    clean_key = re.sub(r'[^0-9a-zA-Z]+', '_', key).strip('_').lower()
    return f'fv_{clean_key}'

key_to_col = {key: normalize_fundament_key(key) for key in keys_to_keep}


def _parse_finviz_page(html):
    """Parse a Finviz quote page HTML string into a fundamentals dict.
    Finviz now splits fundamentals across multiple snapshot-table2 tables.
    """
    soup = BeautifulSoup(html, 'html.parser')
    tables = soup.find_all('table', class_='snapshot-table2')
    if not tables:
        raise RuntimeError('snapshot-table2 not found on page')

    raw = {}
    for table in tables:
        for row in table.find_all('tr'):
            cells = row.find_all('td')
            if len(cells) >= 2:
                key = cells[0].get_text(strip=True)
                val = cells[1].get_text(strip=True)
                if key:
                    raw[key] = val

    # Company name from page title if not in table
    if 'Company' not in raw:
        title_tag = soup.find('title')
        if title_tag:
            title_text = title_tag.get_text(strip=True)
            # title format: "AAPL - Apple Inc Stock Price and Quote"
            parts = title_text.split('-')
            if len(parts) >= 2:
                raw['Company'] = parts[1].replace('Stock Price and Quote', '').strip()

    return raw


def scrape_finviz_fundamentals(ticker, headers=None, timeout=20, retries=2):
    """
    Scrape Finviz quote page directly.
    If the ticker has an exchange suffix (e.g. .DE, .MI) and returns 404,
    retry with the suffix stripped.
    Falls back to finvizfinance if direct scrape fails.
    Returns (fundament_dict, error_message).
    """
    if headers is None:
        headers = {
            'User-Agent': (
                'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
                'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'
            )
        }

    candidates = [ticker]
    # For suffixed tickers, also try the base ticker (e.g. HEN3.DE -> HEN3)
    if '.' in ticker:
        base = ticker.rsplit('.', 1)[0]
        if base and base not in candidates:
            candidates.append(base)

    last_error = None
    for candidate in candidates:
        url = f'https://finviz.com/quote.ashx?t={candidate}'
        for attempt in range(retries + 1):
            try:
                resp = requests.get(url, headers=headers, timeout=timeout)
                resp.raise_for_status()
                raw = _parse_finviz_page(resp.text)
                return raw, None
            except requests.HTTPError as e:
                last_error = f"{candidate}: {type(e).__name__}: {e}"
                if attempt < retries:
                    time.sleep(1.5)
            except Exception as e:
                last_error = f"{candidate}: {type(e).__name__}: {e}"
                if attempt < retries:
                    time.sleep(1.5)

    # fallback to finvizfinance (original and base ticker)
    for candidate in candidates:
        try:
            stock_obj = finvizfinance(candidate)
            stock_fundament = stock_obj.ticker_fundament()
            if stock_fundament:
                return dict(stock_fundament), None
        except Exception as e:
            last_error += f" | finvizfinance({candidate}): {type(e).__name__}: {e}"

    return {}, last_error


fundamentals_rows = []
failed_tickers = []
failed_errors = []

for i, t in enumerate(tickers):
    raw_fundament, err = scrape_finviz_fundamentals(t)
    if err:
        failed_tickers.append(t)
        failed_errors.append(err)
    else:
        row = {'symbol': t}
        for key in keys_to_keep:
            row[key_to_col[key]] = raw_fundament.get(key)
        fundamentals_rows.append(row)

    if (i + 1) % 25 == 0:
        print(f'Processed {i + 1}/{len(tickers)} tickers; failures so far: {len(failed_tickers)}')

    time.sleep(0.35)

fundamentals_df = pd.DataFrame(fundamentals_rows)

fundamentals_cache_path = Path('14_stocks_analysis/fundamentals_cache.csv')
fundamentals_cache_path.parent.mkdir(parents=True, exist_ok=True)
fundamentals_df.to_csv(fundamentals_cache_path, index=False)

print(f'Fundamentals downloaded for {len(fundamentals_df)} tickers')
print(f'Fundamentals cache saved to: {fundamentals_cache_path}')

if failed_tickers:
    print('Failed tickers:')
    print(failed_tickers)
    print('\nFirst few error messages:')
    for t, e in zip(failed_tickers[:5], failed_errors[:5]):
        print(f'  {t}: {e}')
else:
    print('No failed tickers.')

KeyboardInterrupt:

In [ ]:
# TODO:
# The remaining failed tickers below are genuinely not available on Finviz
# (either delisted, acquired, or not covered for the exchange).
# For now they are excluded from the fundamentals cache.
# Future improvement: fallback to yfinance for missing fundamentals.

# Latest failed tickers after direct Finviz scraping + suffix stripping:
# ['HEN3.DE', 'HEN.DE', 'BEI.DE', 'LISN.SW', 'KALV', 'DGICB', 'FFIC', 'XOMA', 'ASRT', 'NFBK']

In [ ]:
# TODO: yahoo finance tickers differs from finviz tickers, look at the below example:
# Fundamentals downloaded for 11 tickers
# Fundamentals cache saved to: 14_stocks_analysis\fundamentals_cache.csv
# Failed tickers:
# ['ADS.DE', 'HEN3.DE', 'HEN.DE', 'BEI.DE'] 
# Need to apply a general solution to align the tickers in the dataframe with the tickers used by finviz,
# for example by removing the market suffixes (.DE, .MI, etc.) before downloading

In [ ]:
# load fundamentals from cache CSV (for tests, avoids repeated API calls)
from pathlib import Path

fundamentals_cache_path = Path('14_stocks_analysis/fundamentals_cache.csv')
fundamentals_df = pd.read_csv(fundamentals_cache_path)

print(f'Loaded fundamentals cache: {fundamentals_cache_path}')
print(f'Rows: {len(fundamentals_df)}')

fundamentals_df.head()

Loaded fundamentals cache: 14_stocks_analysis\fundamentals_cache.csv
Rows: 369

,symbol,fv_company,fv_sector,fv_industry,fv_p_e,fv_eps_ttm,fv_perf_week,fv_market_cap,fv_forward_p_e,fv_perf_month,...,fv_prev_close,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change
0,HST,Host Hotels & Resorts Inc,NaN,NaN,16.08,1.49,5.83%,16.42B,22.63,9.45%,...,23.85,0.88,12.92%,8.74M,23.97,"Aug 26, 1968",2.88%1.50%,NaN,"13,127,258",NaN
1,NFLX,Netflix Inc,NaN,NaN,22.22,3.17,0.33%,293.68B,18.59,-6.35%,...,72.61,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN
2,FOX,Fox Corp,NaN,NaN,14.92,3.83,2.38%,25.52B,9.69,-2.07%,...,57.14,0.65,1.59%,1.09M,57.22,"Mar 13, 2019",24.57%15.71%,NaN,"1,229,952",NaN
3,FOXA,Fox Corp,NaN,NaN,16.73,3.83,2.79%,25.52B,10.90,-1.28%,...,63.98,0.65,2.38%,4.70M,64.15,"Mar 12, 2019",24.49%15.61%,NaN,"4,128,837",NaN
4,MUSA,Murphy USA Inc,NaN,NaN,16.67,32.84,3.50%,10.07B,17.82,4.75%,...,544.73,3.47,7.16%,262.52K,547.67,"Aug 19, 2013",12.90%12.84%,NaN,"216,478",NaN

In [ ]:
# merge fundamentals into df on symbol
df = df.merge(fundamentals_df, on='symbol', how='left')

print(f'Merged dataframe rows: {len(df)}')
print(f'Columns after merge: {len(df.columns)}')

df.head()

Merged dataframe rows: 410
Columns after merge: 75

,date,symbol,stock,fair_value_(%),z-score,f-score,m-score,value_generation,market_cap_(B),count,...,fv_prev_close,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change
0,2026-10-01,HST,"Host Hotels & Resorts, Inc.",0.75,2.17,7.0,-3.27,Robust,16.60,1.0,...,23.85,0.88,12.92%,8.74M,23.97,"Aug 26, 1968",2.88%1.50%,NaN,"13,127,258",NaN
1,2026-10-01,NFLX,"Netflix, Inc.",32.40,9.24,7.0,-2.31,Robust,295.47,1.0,...,72.61,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN
2,2026-10-01,FOX,Fox Corporation,15.41,3.09,7.0,-2.69,Robust,24.66,1.0,...,57.14,0.65,1.59%,1.09M,57.22,"Mar 13, 2019",24.57%15.71%,NaN,"1,229,952",NaN
3,2026-10-01,FOXA,Fox Corporation,14.56,3.09,7.0,-2.69,Robust,27.65,1.0,...,63.98,0.65,2.38%,4.70M,64.15,"Mar 12, 2019",24.49%15.61%,NaN,"4,128,837",NaN
4,2026-10-01,MUSA,Murphy USA Inc.,2.83,7.43,8.0,-2.55,Robust,10.10,1.0,...,544.73,3.47,7.16%,262.52K,547.67,"Aug 19, 2013",12.90%12.84%,NaN,"216,478",NaN

In [ ]:
# quick check: tickers used in batch download
print('Tickers:', tickers)
print('Number of tickers:', len(tickers))

Tickers: ['HST', 'NFLX', 'FOX', 'FOXA', 'MUSA', 'AMN', 'SEDG', 'WSBC', 'KEEL', 'DASH', 'DDOG', 'CSU', 'SAPG', 'CHD', 'PERI', 'ATRA', 'OBEL', 'NTGR', 'IDT', 'TATT', 'LVS', 'STLA', 'BMRC', 'EXC', 'AXP', 'FFIC', 'VICI', 'POET', 'CYRX', 'GRAB', 'STX', 'ES', 'ADTN', 'FAGRO', 'LPTH', 'MIKK', 'GDYN', 'EL.PA', 'IVZ', 'FMC', 'VLY', 'ECOR', 'DLTR', 'AES', 'PAYC', 'BAS', 'EFOR', 'NFBK', 'SAP', 'LULU', 'MAYS', 'RI', 'MOH', 'BBWI', 'LEN', 'EXLS', 'ORLY', 'HIFS', 'CMS', 'C', 'BKNG', 'INTU', 'OSBC', 'BMNR', 'CPS', 'PODD', 'TSCO', 'CRWD', 'RUN', 'CGNX', 'TSM', 'TMUS', 'RCKY', 'APH', 'SIFY', 'GLPU', 'RTX', 'PAGP', 'NKTR', 'UEN.F', 'COLB', 'SST', 'MTCH', 'CHCI', 'DDD', 'CLSK', 'DECK', 'SMR', 'DELL', 'RGS', 'TSAT', 'DAKT', 'PUMG', 'PROV', 'WULF', 'BA', 'ADC', 'IGD.MI', 'CSIQ', 'INCY', 'MCFT', 'RBLK', 'PLTR', 'CMPR', 'CVBF', 'COIN', 'ABBV', 'XYZ', 'UTMD', 'WIX', 'MOS', 'SYNA', 'EW', 'ALGT', 'WEX', 'PLD', 'LUNR', 'AXGN', 'NVAX', 'DUOT', 'LMT', 'IONS', 'DHR', 'PCTY', 'OREP', 'NOW', 'TSLXRGTI', 'ANGO', 'AVAV', 'HUBS', 'J', 'SE', 'FUSB', 'AAPL', 'KR', 'SG', 'ORCL', 'RIVN', '0700.HQ', 'ABNB', 'CSTL', 'MGM', 'DKNG', 'UBER', 'VEEV', 'GNRC', 'MMS', 'ISSC', 'FLUX', 'VECO', 'SBLK', 'SSBI', 'ENPH', 'CASY', 'WING', 'WYNN', 'TWIN', 'FE', 'PL', 'AN', 'BBW', 'MTRX', 'AUPH', 'WDAY', 'MDB', 'AVGO', 'ASRT', 'BUSE', 'BJRI', 'CYTK', 'CTSH', 'TME', 'MTD', 'ADSK', 'VCYT', 'AOO', 'AMSC', 'AMP.MI', 'ASYS', 'HCSG', 'HAFC', 'CARR', 'FIGMA', 'ESEA', 'LYFT', 'BSX', 'RKLB', 'CPRT', 'CRWV', 'TTD', 'RTO', 'TACO', 'STRS', 'VNA.DE', 'PDD', 'U', 'SFD', 'SWK', 'SPSC', 'MORN', 'OCFC', 'EXTR', 'APPS', 'XOMA', 'MELI', 'SOUN', 'WMT', 'BPOP', 'LIVN', 'GLNG', 'VC', 'BE', 'VTRS', 'PSTG', 'TITN', 'TWLO', 'NEXI.MI', 'REY.MI', 'INVA', 'OKLO', 'SHAK', 'SHW', 'FCEL', 'F', 'BROS', 'CLMT', 'VOC', 'IBM', 'GLRE', 'AMD', 'CLX', 'MQ', 'LQDT', 'CRM', 'FTK', 'MCD', 'OVV', 'VST', 'PPC', 'FIG', 'ALCO', 'WLK', 'ADBE', 'PFE', 'MATW', 'AZO', 'GCBC', 'QRVO', 'EBS', 'SHBI', 'PTC', 'ANET', 'ECMPA', 'TSSI', 'RIOT', 'PNR', 'ASTE', 'WRLD', 'SSRM', 'QCOM', 'ASMB', 'MHK', 'EPRT', 'TRGP', 'ACN', 'ALKS', 'RMS', 'KTOS', 'YUM', 'LWLG', 'ZS', 'LBTYA', 'PATH', 'COHR', 'SHEN', 'FSTR', 'SNDA', 'FICO', 'BUD', 'SILC', 'AMRX', 'EL', 'SAM', 'NKE', 'NRG', 'CCL', 'NVDA', 'CIVB', 'CDP', 'BLDR', 'NU', 'WKL', 'AS', 'BALL', 'RAMP', 'BMI', 'APA', 'STZ', 'TOP', 'APP', 'KER', 'ATLO', 'CRCL', 'BRO', 'CLDX', 'CPNG', 'SRPT', 'STAA', 'RDDT', 'HIMS', 'ULTA', 'EEFT', 'AAL', 'IPGP', 'O', 'SOFI', 'WH', 'KALV', 'FIS', 'NVO', 'AAON', 'APLD', 'JOUT', 'DOCU', 'LOW', 'SNDX', 'PEG', 'ZVRA', 'RNG', 'CBT', 'BIIB', 'STM', 'GME', 'IEX', 'NCLH', 'PLSE', '7974.T', 'CBRL', 'G24.DE', 'HPQ', 'P911.DE', 'AMZR', 'TTAN', 'TTWO', 'ZUMZ', 'BB', 'ENTA', 'DGICB', 'BAC', 'KHC', 'HAS', 'INTG', 'BLK', 'CRDO', 'ROKU', 'ACLS', 'FLG', 'PYPL', 'LCNB', 'PEP', 'UBI.PA', 'UMI', 'TEP', 'SARO', 'WTBA', 'QURE', 'GDD', 'VMC', 'AST', 'OMER', 'CRVS', 'ROST', 'CFBK', 'MSFT', 'AFX', 'MC.PA', 'DVN', 'BABA', 'ONDS', 'IT', 'WBD', 'SCVL', 'CTRN', 'OCC', 'AON', 'XPEL', 'VRSK', 'FIBK', 'QLYS', 'WDC', 'MVBF', 'DRH', 'PANW', 'CORT', 'FR', 'TU', 'GPN', 'FTNT', 'ROL', 'AFX.DE', 'ILMN', 'ATNI', 'DPKO', 'TIGO', 'CAT', 'DUOL', 'NET', 'PGR', 'SPCX', 'EZJ']
Number of tickers: 410

In [ ]:
# quick check: cached fundamentals columns (prefixed with fv_)
fundamentals_df.columns.tolist() #[:20]

['symbol',
 'fv_company',
 'fv_sector',
 'fv_industry',
 'fv_p_e',
 'fv_eps_ttm',
 'fv_perf_week',
 'fv_market_cap',
 'fv_forward_p_e',
 'fv_perf_month',
 'fv_short_float',
 'fv_perf_quarter',
 'fv_p_s',
 'fv_eps_this_y',
 'fv_short_ratio',
 'fv_perf_half_y',
 'fv_p_b',
 'fv_roa',
 'fv_perf_ytd',
 'fv_p_c',
 'fv_roe',
 'fv_52w_high',
 'fv_perf_year',
 'fv_p_fcf',
 'fv_eps_past_3_5y',
 'fv_roic',
 'fv_52w_low',
 'fv_perf_3y',
 'fv_dividend_est',
 'fv_ev_ebitda',
 'fv_sales_past_3_5y',
 'fv_volatility_w',
 'fv_volatility_m',
 'fv_perf_5y',
 'fv_dividend_ttm',
 'fv_ev_sales',
 'fv_eps_y_y_ttm',
 'fv_oper_margin',
 'fv_atr_14',
 'fv_perf_10y',
 'fv_quick_ratio',
 'fv_sales_y_y_ttm',
 'fv_profit_margin',
 'fv_rsi_14',
 'fv_recom',
 'fv_dividend_gr_3_5y',
 'fv_current_ratio',
 'fv_eps_q_q',
 'fv_sma20',
 'fv_beta',
 'fv_payout',
 'fv_debt_eq',
 'fv_sales_q_q',
 'fv_sma50',
 'fv_rel_volume',
 'fv_prev_close',
 'fv_lt_debt_eq',
 'fv_sma200',
 'fv_avg_volume',
 'fv_price',
 'fv_ipo',
 'fv_eps_sales_surpr',
 'fv_trades',
 'fv_volume',
 'fv_change']

In [ ]:
# preview merged fundamentals for first rows
df.filter(regex='^fv_').head()

,fv_company,fv_sector,fv_industry,fv_p_e,fv_eps_ttm,fv_perf_week,fv_market_cap,fv_forward_p_e,fv_perf_month,fv_short_float,...,fv_prev_close,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change
0,Host Hotels & Resorts Inc,NaN,NaN,16.08,1.49,5.83%,16.42B,22.63,9.45%,5.83%,...,23.85,0.88,12.92%,8.74M,23.97,"Aug 26, 1968",2.88%1.50%,NaN,"13,127,258",NaN
1,Netflix Inc,NaN,NaN,22.22,3.17,0.33%,293.68B,18.59,-6.35%,1.99%,...,72.61,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN
2,Fox Corp,NaN,NaN,14.92,3.83,2.38%,25.52B,9.69,-2.07%,7.02%,...,57.14,0.65,1.59%,1.09M,57.22,"Mar 13, 2019",24.57%15.71%,NaN,"1,229,952",NaN
3,Fox Corp,NaN,NaN,16.73,3.83,2.79%,25.52B,10.90,-1.28%,24.49%,...,63.98,0.65,2.38%,4.70M,64.15,"Mar 12, 2019",24.49%15.61%,NaN,"4,128,837",NaN
4,Murphy USA Inc,NaN,NaN,16.67,32.84,3.50%,10.07B,17.82,4.75%,5.32%,...,544.73,3.47,7.16%,262.52K,547.67,"Aug 19, 2013",12.90%12.84%,NaN,"216,478",NaN

In [ ]:
df.shape

(410, 75)

In [ ]:
# drop rows where all values are nan
df = df.dropna(how='all', subset=df.filter(regex='^fv_').columns)

In [ ]:
df.shape

(369, 75)

In [ ]:
# count how many symbols did not receive fundamentals
missing_fv = df['fv_company'].isna().sum() if 'fv_company' in df.columns else None
print('Symbols with missing fundamentals:', missing_fv)

Symbols with missing fundamentals: 0

In [ ]:
# # print failed tickers again (separate output cell)
# print(failed_tickers)

In [ ]:
# show first rows from fundamentals cache dataframe
fundamentals_df.head()

,symbol,fv_company,fv_sector,fv_industry,fv_p_e,fv_eps_ttm,fv_perf_week,fv_market_cap,fv_forward_p_e,fv_perf_month,...,fv_prev_close,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change
0,HST,Host Hotels & Resorts Inc,NaN,NaN,16.08,1.49,5.83%,16.42B,22.63,9.45%,...,23.85,0.88,12.92%,8.74M,23.97,"Aug 26, 1968",2.88%1.50%,NaN,"13,127,258",NaN
1,NFLX,Netflix Inc,NaN,NaN,22.22,3.17,0.33%,293.68B,18.59,-6.35%,...,72.61,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN
2,FOX,Fox Corp,NaN,NaN,14.92,3.83,2.38%,25.52B,9.69,-2.07%,...,57.14,0.65,1.59%,1.09M,57.22,"Mar 13, 2019",24.57%15.71%,NaN,"1,229,952",NaN
3,FOXA,Fox Corp,NaN,NaN,16.73,3.83,2.79%,25.52B,10.90,-1.28%,...,63.98,0.65,2.38%,4.70M,64.15,"Mar 12, 2019",24.49%15.61%,NaN,"4,128,837",NaN
4,MUSA,Murphy USA Inc,NaN,NaN,16.67,32.84,3.50%,10.07B,17.82,4.75%,...,544.73,3.47,7.16%,262.52K,547.67,"Aug 19, 2013",12.90%12.84%,NaN,"216,478",NaN

In [ ]:
# number of prefixed fundamentals columns
len([c for c in fundamentals_df.columns if c.startswith('fv_')])

64

In [ ]:
# # all listed keys in stock_fundament
# """
# dict_keys(['Company', 'Sector', 'Industry', 'Country', 'Exchange', 'Index', 'P/E', 'EPS (ttm)', 
# 'Insider Own', 'Shs Outstand', 'Perf Week', 'Market Cap', 'Forward P/E', 'EPS next Y', 'Insider Trans', 'Shs Float', 'Perf Month', 
# 'Enterprise Value', 'PEG', 'EPS next Q', 'Inst Own', 'Short Float', 'Perf Quarter', 'Income', 'P/S', 'EPS this Y', 'Inst Trans', 
# 'Short Ratio', 'Perf Half Y', 'Sales', 'P/B', 'EPS next Y Percentage', 'ROA', 'Short Interest', 'Perf YTD', 'Book/sh', 'P/C', 
# 'EPS next 5Y', 'ROE', '52W High', 'Perf Year', 'Cash/sh', 'P/FCF', 'EPS past 3/5Y', 'ROIC', '52W Low', 'Perf 3Y', 'Dividend Est.', 
# 'EV/EBITDA', 'Sales past 3/5Y', 'Gross Margin', 'Volatility W', 'Volatility M', 'Perf 5Y', 'Dividend TTM', 'EV/Sales', 'EPS Y/Y TTM', 
# 'Oper. Margin', 'ATR (14)', 'Perf 10Y', 'Dividend Ex-Date', 'Quick Ratio', 'Sales Y/Y TTM', 'Profit Margin', 'RSI (14)', 'Recom', 
# 'Dividend Gr. 3/5Y', 'Current Ratio', 'EPS Q/Q', 'SMA20', 'Beta', 'Target Price', 'Payout', 'Debt/Eq', 'Sales Q/Q', 'SMA50', 'Rel Volume', 
# 'Prev Close', 'Employees', 'LT Debt/Eq', 'Earnings', 'SMA200', 'Avg Volume', 'Price', 'IPO', 'Option/Short', 'EPS/Sales Surpr.', 'Trades', 'Volume', 'Change'])
# """;

# # keys to keep in stock_fundament
# keys_to_keep = ['Company', 'Sector', 'Industry', 'P/E', 'EPS (ttm)', 
# 'Perf Week', 'Market Cap', 'Forward P/E', 'EPS next Y', 'Perf Month', 
# 'Short Float', 'Perf Quarter', 'P/S', 'EPS this Y',  
# 'Short Ratio', 'Perf Half Y', 'P/B', 'ROA', 'Perf YTD', 'P/C', 
# 'ROE', '52W High', 'Perf Year', 'P/FCF', 'EPS past 3/5Y', 'ROIC', '52W Low', 'Perf 3Y', 'Dividend Est.', 
# 'EV/EBITDA', 'Sales past 3/5Y', 'Volatility W', 'Volatility M', 'Perf 5Y', 'Dividend TTM', 'EV/Sales', 'EPS Y/Y TTM', 
# 'Oper. Margin', 'ATR (14)', 'Perf 10Y', 'Quick Ratio', 'Sales Y/Y TTM', 'Profit Margin', 'RSI (14)', 'Recom', 
# 'Dividend Gr. 3/5Y', 'Current Ratio', 'EPS Q/Q', 'SMA20', 'Beta', 'Payout', 'Debt/Eq', 'Sales Q/Q', 'SMA50', 'Rel Volume', 
# 'Prev Close', 'LT Debt/Eq', 'SMA200', 'Avg Volume', 'Price', 'IPO', 'EPS/Sales Surpr.', 'Trades', 'Volume', 'Change']

# # TODO: 'Perf Month', 'Perf Quarter', 'Perf YTD', 'Perf Half Y', 'Perf Year', 'Perf 3Y', 'Perf 5Y', 'Perf 10Y' should be converted to numeric, removing the "%" character, 
# # then used as one of the first filters to keep only stocks with negative performance

# # TODO: 'EPS past 3/5Y': '37.29% 8.84%' should be split into two separate columns, one for 3Y and one for 5Y, but for now we will keep it as is
# # TODO: 'Sales past 3/5Y': '7.21% 9.24%' should be split into two separate columns, one for 3Y and one for 5Y, but for now we will keep it as is

# stock_fundament_filtered = {key: stock_fundament[key] for key in keys_to_keep if key in stock_fundament}

# print(stock_fundament_filtered)

In [ ]:
# drop columns price (if exists) because we will keep only fv_price from fundamentals
if 'price' in df.columns:
    df = df.drop(columns=['price'])

In [ ]:
# df.info()

In [ ]:
# # sample of merged dataframe with selected fundamentals
# cols_to_show = [c for c in ['symbol', 'stock', 'fv_company', 'fv_sector', 'fv_industry', 'fv_p_e', 'fv_roe', 'fv_profit_margin'] if c in df.columns]
# df[cols_to_show].head(10)

In [ ]:
# # rows in merge where at least one fundamentals value exists
# fv_cols = [c for c in df.columns if c.startswith('fv_')]
# df[df[fv_cols].notna().any(axis=1)].head() if fv_cols else df.head()

In [ ]:
# # list prefixed fundamentals columns
# [c for c in df.columns if c.startswith('fv_')]

In [ ]:
# select all columns that start with "fv_perf_"
perf_cols = [c for c in df.columns if c.startswith('fv_perf_')]

# convert fv_perf_ columns to numeric, removing the "%" character
for col in perf_cols:
    df[col] = pd.to_numeric(df[col].str.replace('%', ''), errors='coerce')

df[perf_cols].head() if perf_cols else df.head()

,fv_perf_week,fv_perf_month,fv_perf_quarter,fv_perf_half_y,fv_perf_ytd,fv_perf_year,fv_perf_3y,fv_perf_5y,fv_perf_10y
0,5.83,9.45,-0.37,16.87,39.22,53.72,55.86,52.96,68.03
1,0.33,-6.35,4.33,-27.52,-24.78,-40.41,95.47,12.26,595.08
2,2.38,-2.07,11.00,-2.24,-11.87,11.61,96.09,46.83,NaN
3,2.79,-1.28,11.60,-1.41,-12.21,12.54,102.88,54.17,NaN
4,3.50,4.75,-12.06,11.51,35.72,44.29,50.24,230.14,689.38

In [ ]:
len(df)

369

In [ ]:
# --- performance filters ---
# keep only rows where one of the performance columns is lower than -20
df = df[df[perf_cols].lt(-20).any(axis=1)]

In [ ]:
len(df)

231

In [ ]:
# df.info()

In [ ]:
# --- market cap filter (stocks list only) ---
# fv_market_cap comes from finviz as a string like "1.50B", "337.71M", etc.
# Convert to billions for comparison; skip if using rankings (already filtered there).
if use_stocks_list and 'fv_market_cap' in df.columns:
    def _parse_mc_to_billions(val):
        if pd.isna(val):
            return None
        s = str(val).strip().upper().replace(',', '')
        if s.endswith('T'):
            return float(s[:-1]) * 1000
        elif s.endswith('B'):
            return float(s[:-1])
        elif s.endswith('M'):
            return float(s[:-1]) / 1000
        elif s.endswith('K'):
            return float(s[:-1]) / 1_000_000
        try:
            return float(s)
        except ValueError:
            return None

    fv_mc_b = df['fv_market_cap'].apply(_parse_mc_to_billions)
    df = df[~(fv_mc_b.notna() & (fv_mc_b < 10))]

In [ ]:
len(df)

93

In [ ]:
# list of symbols in the final dataframe
final_symbols = df['symbol'].tolist()
final_symbols

['NFLX',
 'DASH',
 'LVS',
 'STLA',
 'VICI',
 'GRAB',
 'STX',
 'ES',
 'EL.PA',
 'AES',
 'PAYC',
 'LULU',
 'MOH',
 'LEN',
 'BKNG',
 'INTU',
 'BMNR',
 'TSCO',
 'TMUS',
 'DECK',
 'DELL',
 'COIN',
 'XYZ',
 'EW',
 'NOW',
 'HUBS',
 'SE',
 'ORCL',
 'RIVN',
 'DKNG',
 'UBER',
 'GNRC',
 'CASY',
 'WDAY',
 'MDB',
 'CTSH',
 'BSX',
 'RKLB',
 'CPRT',
 'CRWV',
 'RTO',
 'PDD',
 'U',
 'SWK',
 'BE',
 'VTRS',
 'TWLO',
 'IBM',
 'CLX',
 'MCD',
 'VST',
 'FIG',
 'ADBE',
 'PFE',
 'AZO',
 'QRVO',
 'ACN',
 'ZS',
 'COHR',
 'FICO',
 'BUD',
 'EL',
 'NKE',
 'NRG',
 'CCL',
 'BALL',
 'APA',
 'STZ',
 'APP',
 'CRCL',
 'BRO',
 'CPNG',
 'RDDT',
 'SOFI',
 'FIS',
 'NVO',
 'DOCU',
 'LOW',
 'STM',
 'GME',
 'TTWO',
 'KHC',
 'CRDO',
 'ROKU',
 'PYPL',
 'BABA',
 'IT',
 'VRSK',
 'WDC',
 'TU',
 'GPN',
 'ROL',
 'ILMN']

In [ ]:
# drop duplicates from final_symbols
final_symbols = list(set(final_symbols))

In [ ]:
import time
import random

def download_yf_batch(symbols, batch_size=5, sleep_sec=2.0, max_retries=3, period='max'):
    """
    Download historical OHLCV data from Yahoo Finance in small sequential batches.
    
    - Downloads `batch_size` tickers at a time with `threads=False`
    - Sleeps `sleep_sec` between batches
    - Retries failed tickers individually with exponential backoff
    - Saves incremental progress to avoid losing data on rate-limit errors
    """
    symbols = list(set(str(s).strip() for s in symbols if s and str(s).strip()))
    failed = []
    all_data = {}

    print(f"Downloading {len(symbols)} tickers in batches of {batch_size}...")

    for i in range(0, len(symbols), batch_size):
        batch = symbols[i:i + batch_size]
        print(f"\nBatch {i // batch_size + 1}/{(len(symbols) - 1) // batch_size + 1}: {batch}")

        for attempt in range(max_retries):
            try:
                batch_data = yf.download(
                    batch,
                    period=period,
                    group_by='ticker',
                    threads=False,       # sequential requests inside the batch
                    progress=False,
                )

                if isinstance(batch_data.columns, pd.MultiIndex):
                    # multiple tickers returned
                    for ticker in batch:
                        if ticker in batch_data.columns.get_level_values(0):
                            all_data[ticker] = batch_data[ticker]
                else:
                    # single ticker returned (flat columns)
                    all_data[batch[0]] = batch_data

                break  # success

            except Exception as e:
                wait = (2 ** attempt) + random.uniform(0, 1)
                print(f"  Attempt {attempt + 1} failed: {e}. Waiting {wait:.1f}s...")
                time.sleep(wait)
                if attempt == max_retries - 1:
                    failed.extend(batch)

        time.sleep(sleep_sec)

    # Retry failed tickers one-by-one with longer delays
    if failed:
        print(f"\nRetrying {len(failed)} failed tickers individually...")
        still_failed = []
        for ticker in failed:
            for attempt in range(max_retries):
                try:
                    t_data = yf.download(ticker, period=period, progress=False, threads=False)
                    if not t_data.empty:
                        all_data[ticker] = t_data
                        break
                except Exception as e:
                    wait = (2 ** attempt) + random.uniform(0, 5)
                    print(f"  {ticker} attempt {attempt + 1} failed: {e}. Waiting {wait:.1f}s...")
                    time.sleep(wait)
                    if attempt == max_retries - 1:
                        still_failed.append(ticker)
            time.sleep(sleep_sec)
        failed = still_failed

    if not all_data:
        raise RuntimeError("No data downloaded.")

    data = pd.concat(all_data, axis=1, names=['Ticker', 'OHLCV'])
    print(f"\nDownloaded {len(all_data)} tickers successfully.")
    if failed:
        print(f"Failed tickers: {failed}")
    return data, failed


# Download historical data for final symbols
data, yf_failed = download_yf_batch(
    final_symbols,
    batch_size=5,
    sleep_sec=2.0,
    period='max'
)

# Save to CSV
data.to_csv("final_symbols.csv")
print("Saved to final_symbols.csv")

Downloading 93 tickers in batches of 5...

Batch 1/19: ['BALL', 'DASH', 'APA', 'SWK', 'STZ']
YF.download() has changed argument auto_adjust default to True

5 Failed downloads:
['BALL', 'DASH', 'APA', 'SWK', 'STZ']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 2/19: ['APP', 'CRCL', 'BRO', 'BE', 'VTRS']

5 Failed downloads:
['BRO', 'CRCL', 'BE', 'VTRS', 'APP']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 3/19: ['CPNG', 'U', 'TWLO', 'RDDT', 'COIN']

5 Failed downloads:
['TWLO', 'RDDT', 'U', 'COIN', 'CPNG']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 4/19: ['XYZ', 'SOFI', 'FIS', 'NVO', 'LVS']

5 Failed downloads:
['FIS', 'NVO', 'LVS', 'XYZ', 'SOFI']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 5/19: ['STLA', 'DOCU', 'LOW', 'EW', 'STM']

5 Failed downloads:
['EW', 'STLA', 'STM', 'DOCU', 'LOW']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 6/19: ['VICI', 'IBM', 'GME', 'NOW', 'CLX']

5 Failed downloads:
['NOW', 'CLX', 'IBM', 'VICI', 'GME']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

Batch 7/19: ['GRAB', 'STX', 'ES', 'TTWO', 'HUBS']

5 Failed downloads:
['GRAB', 'STX', 'ES', 'TTWO', 'HUBS']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

KeyboardInterrupt:

In [ ]:
# Load the CSV with MultiIndex columns (Tickers, OHLCV)
data = pd.read_csv("final_symbols.csv", header=[0,1], index_col=0)

# Drop any rows that are completely NaN (e.g. 'Date' row)
data = data.dropna(how='all')

# Convert all values to float
data = data.astype(float)

# Keep the ticker list aligned with the actual columns in the loaded data
loaded_tickers = [str(t) for t in data.columns.get_level_values(0).dropna().unique()]
resolved_tickers = list(dict.fromkeys(loaded_tickers))

data.tickers = resolved_tickers
final_symbols = resolved_tickers

# Show the result
data.head()

Ticker       SE                        BUD                        ...  NRG  \
OHLCV      Open High Low Close Volume Open High Low Close Volume  ... Open
Date                                                              ...
1962-01-02  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...  NaN
1962-01-03  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...  NaN
1962-01-04  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...  NaN
1962-01-05  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...  NaN
1962-01-08  NaN  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN  ...  NaN

Ticker                             EW
OHLCV      High Low Close Volume Open High Low Close Volume
Date
1962-01-02  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN
1962-01-03  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN
1962-01-04  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN
1962-01-05  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN
1962-01-08  NaN NaN   NaN    NaN  NaN  NaN NaN   NaN    NaN

[5 rows x 465 columns]

In [ ]:
from market_profile import MarketProfile

# calculate POC price for each ticker in final_symbols
poc = {}
# market_profiles = {} # need to store the market profile objects for later use in the notebook (plotting, etc.) 

for ticker in final_symbols:
    try:
        ticker_data = data[ticker].dropna()
        if ticker_data.empty:
            print(f"No data available for {ticker}.")
            continue

        mp = MarketProfile(ticker_data)
        mp_slice = mp[ticker_data.index.min():ticker_data.index.max()]
        # market_profiles[ticker] = mp_slice

        # Different versions can expose POC differently; handle common cases
        if hasattr(mp_slice, 'poc_price'):
            poc[ticker] = mp_slice.poc_price
        # elif hasattr(mp_slice, 'profile') and 'POC' in mp_slice.profile:
        #     poc[ticker] = mp_slice.profile['POC']
        # elif hasattr(mp_slice, '__getitem__'):
        #     try:
        #         poc[ticker] = mp_slice['POC']
        #     except Exception:
        #         poc[ticker] = None
        else:
            poc[ticker] = None

    except KeyError:
        print(f"Data for {ticker} not found in the dataset.")

In [ ]:
# poc dict to dataframe
poc_df = pd.DataFrame.from_dict(poc, orient='index', columns=['poc_price']).reset_index().rename(columns={'index': 'symbol'})

poc_df.head()

  symbol  poc_price
0     SE      35.90
1    BUD      52.45
2   CRDO     238.00
3    NKE       0.20
4   ADBE       5.20

In [ ]:
# merge poc_df with df on symbol
df = df.merge(poc_df, on='symbol', how='left')

df.head()

,date,symbol,stock,fair_value_(%),z-score,f-score,m-score,value_generation,market_cap_(B),count,...,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change,poc_price
0,2026-10-01,NFLX,"Netflix, Inc.",32.4,9.24,7.0,-2.31,Robust,295.47,1.0,...,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN,0.35
1,NaT,CRDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,-5.82%,7.26M,169.70,"Jan 27, 2022",2.21%1.21%,NaN,"6,411,211",NaN,238.00
2,NaT,AZO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-4.63%,266.37K,3120.59,"Apr 02, 1991",3.64%-1.60%,NaN,"258,767",NaN,80.25
3,NaT,SOFI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.31,-20.79%,54.09M,14.55,"Nov 30, 2020",11.42%8.13%,NaN,"59,575,998",NaN,6.95
4,NaT,VRSK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,1.63%,1.37M,190.90,"Oct 07, 2009",2.36%0.28%,NaN,"1,471,711",NaN,25.85

In [ ]:
# --- poc filter ---
# keep only rows where poc_price is lower than fv_price
df = df[df['poc_price'] < df['fv_price']]

In [ ]:
# TODO: optional next step: inside trader data can be fetched in a separate batch process

In [ ]:
# print length of dataframe
print("Number of rows in the dataframe:", len(df))

# print lenght of unique symbols in the dataframe (for comparison with the original dataframe)
print("Number of unique symbols in the dataframe:", df['symbol'].nunique())

Number of rows in the dataframe: 70
Number of unique symbols in the dataframe: 70

In [ ]:
df.head(10)

,date,symbol,stock,fair_value_(%),z-score,f-score,m-score,value_generation,market_cap_(B),count,...,fv_lt_debt_eq,fv_sma200,fv_avg_volume,fv_price,fv_ipo,fv_eps_sales_surpr,fv_trades,fv_volume,fv_change,poc_price
0,2026-10-01,NFLX,"Netflix, Inc.",32.4,9.24,7.0,-2.31,Robust,295.47,1.0,...,0.46,-14.90%,36.77M,70.53,"May 23, 2002",1.73%-0.17%,NaN,"44,151,267",NaN,0.35
2,NaT,AZO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-4.63%,266.37K,3120.59,"Apr 02, 1991",3.64%-1.60%,NaN,"258,767",NaN,80.25
3,NaT,SOFI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.31,-20.79%,54.09M,14.55,"Nov 30, 2020",11.42%8.13%,NaN,"59,575,998",NaN,6.95
4,NaT,VRSK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,1.63%,1.37M,190.90,"Oct 07, 2009",2.36%0.28%,NaN,"1,471,711",NaN,25.85
5,NaT,ROKU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,23.24%,2.16M,154.54,"Sep 28, 2017",78.39%4.40%,NaN,"1,694,642",NaN,64.50
6,NaT,EL.PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.19,14.00%,3.02M,104.54,"Nov 17, 1995",22.22%2.31%,NaN,"2,845,765",NaN,10.25
7,NaT,MDB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.01,-0.64%,2.15M,337.57,"Oct 19, 2017",17.62%5.00%,NaN,"2,791,490",NaN,334.70
11,NaT,TWLO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.12,33.58%,2.89M,244.37,"Jun 23, 2016",11.06%4.76%,NaN,"4,593,579",NaN,42.75
12,NaT,CTSH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,10.47%,7.51M,66.03,"Jun 19, 1998",-0.54%0.00%,NaN,"5,323,775",NaN,2.30
13,NaT,VTRS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.83,19.59%,9.26M,18.66,"Mar 17, 1980",14.79%2.21%,NaN,"9,422,361",NaN,8.40

In [ ]:
# # TODO:
# # Warren Buffett Ã¢â‚¬â€ Quality Compounder Stock Screener
# All of the following: # Quality growth stocks with strong fundamentals
#   Debt Ratio < 0.5 --> 'fv_debt_eq'
#   EPS Basic > EPS Basic (4Q ago) by at least 10 % --> 'fv_eps_past_3_5y' < 1.1 * 'fv_eps_this_y'
#   FCF to Net Income > 0.1 --> 'fv_p_fcf'/ 'fv_eps_this_y' > 0.1
#   PE Ratio TTM < 25 --> 'fv_p_e' < 25
#   Market Cap > 500m --> 
#   Earnings Per Share, Basic (4Q ago) > Earnings Per Share, Basic (8Q ago) --> 
#   Free Cash Flow > 0 --> 
#   Earnings Per Share, Basic > 0 --> 
#   D TTM ROIC (Lower), Line Ã¢â€°Â¥ 0.1 --> 
#   D TTM ROE (Lower), Line Ã¢â€°Â¥ 0.15 --> 

# list of column names in the dataframe with fundamentals data:
# list_fundamental_data = ['symbol',
#  'fv_company',
#  'fv_sector',
#  'fv_industry',
#  'fv_p_e',
#  'fv_eps_ttm',
#  'fv_perf_week',
#  'fv_market_cap',
#  'fv_forward_p_e',
#  'fv_perf_month',
#  'fv_short_float',
#  'fv_perf_quarter',
#  'fv_p_s',
#  'fv_eps_this_y',
#  'fv_short_ratio',
#  'fv_perf_half_y',
#  'fv_p_b',
#  'fv_roa',
#  'fv_perf_ytd',
#  'fv_p_c',
#  'fv_roe',
#  'fv_52w_high',
#  'fv_perf_year',
#  'fv_p_fcf',
#  'fv_eps_past_3_5y',
#  'fv_roic',
#  'fv_52w_low',
#  'fv_perf_3y',
#  'fv_dividend_est',
#  'fv_ev_ebitda',
#  'fv_sales_past_3_5y',
#  'fv_volatility_w',
#  'fv_volatility_m',
#  'fv_perf_5y',
#  'fv_dividend_ttm',
#  'fv_ev_sales',
#  'fv_eps_y_y_ttm',
#  'fv_oper_margin',
#  'fv_atr_14',
#  'fv_perf_10y',
#  'fv_quick_ratio',
#  'fv_sales_y_y_ttm',
#  'fv_profit_margin',
#  'fv_rsi_14',
#  'fv_recom',
#  'fv_dividend_gr_3_5y',
#  'fv_current_ratio',
#  'fv_eps_q_q',
#  'fv_sma20',
#  'fv_beta',
#  'fv_payout',
#  'fv_debt_eq',
#  'fv_sales_q_q',
#  'fv_sma50',
#  'fv_rel_volume',
#  'fv_prev_close',
#  'fv_lt_debt_eq',
#  'fv_sma200',
#  'fv_avg_volume',
#  'fv_price',
#  'fv_ipo',
#  'fv_eps_sales_surpr',
#  'fv_trades',
#  'fv_volume',
#  'fv_change']

In [ ]:
# # TODO:
# # Peter Lynch Ã¢â‚¬â€ GARP (Growth at a Reasonable Price) Stock Screener
# All of the following: # Growth at a Reasonable Price using Peter LynchÃ¢â‚¬â„¢s core principles
#   EPS Basic > EPS Basic (4Q ago) by at least 25 %
#   PE Ratio TTM Ã¢â€°Â¤ 30
#   Revenue > Revenue (4Q ago) by at least 15 %
#   Debt Ratio < 1
#   Market-Cap Ã¢â€°Â¥ 500m
#   Earnings Per Share, Basic > 0
#   Free Cash Flow > 0

In [ ]:
# # TODO: 10X Stock Screener
# 1. Size Effect, "Small-cap stocks outperform medium and large companies in 11 out of 12 cases", Smaller stocks tend to perform better, but it's not the only contributor.
# 2. Value Effect, "A low book-to-market value (B/M < 1), i.e., low equity and relatively high market cap, implies that investors are paying more for a company than its net assets are worth."
# 3. Free Cash Flow Yield, THE MOST IMPORTANT FACTOR, FCP/P ratio -  a profitability metric used to assess the attractiveness of a stock based on its cash-generating ability relative to its share price
# 4. â€¦â€¦ paper

In [ ]:
import plotly.io as pio
pio.renderers.default = 'vscode'
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
# function to calculate 10 years and 5 years ago dates
from datetime import datetime, timedelta

def find_date_years_ago(years):
    today = datetime.today()
    try:
        return today.replace(year=today.year - years)
    except ValueError:
        # Handle February 29 for leap years
        return today.replace(month=2, day=28, year=today.year - years)
    
# call the function to find the date 10 years ago and 5 years ago
date_10_years_ago = find_date_years_ago(10) 
date_5_years_ago = find_date_years_ago(5)

# print the dates
print("Date 10 years ago:", date_10_years_ago.strftime('%Y-%m-%d'))
print("Date 5 years ago:", date_5_years_ago.strftime('%Y-%m-%d'))

Date 10 years ago: 2016-10-17
Date 5 years ago: 2021-10-17

In [ ]:
def plot_volume_profile(ticker):
    # Use the stock data from our df
    df_stock = data[ticker].dropna()

    # Convert the stock to datetime if needed
    if not isinstance(df_stock.index, pd.DatetimeIndex):
        df_stock.index = pd.to_datetime(df_stock.index)

    # plot
    hist = go.Histogram(
        y=df_stock['Close'],
        x=df_stock['Volume'],
        nbinsy=150,
        orientation='h',
        name='Volume Profile',
        marker_color='#B0C4DE',
        opacity=0.5,
        xaxis='x2',
    )

    line = go.Scatter(
        x=df_stock.index,
        y=df_stock['Close'],
        mode='lines',
        name='Close',
        marker_color='blue',
        xaxis='x',
        yaxis='y',
    )

    fig = go.Figure([hist, line])

    fig.update_layout(
        xaxis=dict(
            title='Date',
            anchor='y',
            domain=[0, 1],
            showgrid=False,
            side='bottom'
        ),
        xaxis2=dict(
            title='Sum of Volume',
            overlaying='x',
            side='top',
            showgrid=False
        ),
        yaxis=dict(
            title='Close Price',
            showgrid=True
        ),
        legend=dict(
            orientation='h',
            yanchor='bottom',
            y=1.02,
            xanchor='right',
            x=1
        ),
        height=600,
        title=f'Volume Profile & {ticker} Close Prices'
    )

    fig.show()

In [ ]:
def plot_volume_profile_10y_5y(ticker):
    # Use the stock data from our df
    df_stock = data[ticker].dropna()

    # Convert the stock to datetime if needed
    if not isinstance(df_stock.index, pd.DatetimeIndex):
        df_stock.index = pd.to_datetime(df_stock.index)

    # Filter data for the last 10 years and 5 years
    df_10y = df_stock[df_stock.index >= date_10_years_ago]
    df_5y = df_stock[df_stock.index >= date_5_years_ago]

    def _plot_single_profile(df_period, period_label, color):
        hist = go.Histogram(
            y=df_period['Close'],
            x=df_period['Volume'],
            nbinsy=150,
            orientation='h',
            name=f'Volume Profile ({period_label})',
            marker_color=color,
            opacity=0.5,
            xaxis='x2',
        )

        line = go.Scatter(
            x=df_period.index,
            y=df_period['Close'],
            mode='lines',
            name='Close',
            marker_color='blue',
            xaxis='x',
            yaxis='y',
        )

        fig = go.Figure([hist, line])

        fig.update_layout(
            xaxis=dict(
                title='Date',
                anchor='y',
                domain=[0, 1],
                showgrid=False,
                side='bottom'
            ),
            xaxis2=dict(
                title='Sum of Volume',
                overlaying='x',
                side='top',
                showgrid=False
            ),
            yaxis=dict(
                title='Close Price',
                showgrid=True
            ),
            legend=dict(
                orientation='h',
                yanchor='bottom',
                y=1.02,
                xanchor='right',
                x=1
            ),
            height=600,
            title=f'Volume Profile ({period_label}) & {ticker} Close Prices'
        )

        fig.show()

    # Separate plots: one for 10Y and one for 5Y
    _plot_single_profile(df_10y, '10Y', '#B0C4DE')
    _plot_single_profile(df_5y, '5Y', '#ADD8E6')

In [ ]:
# --- chart printing ---
from pathlib import Path
from IPython.display import Image, display

output_dir = Path('asset')
output_dir.mkdir(parents=True, exist_ok=True)

failed_chart_tickers = []

for ticker in df.symbol.dropna().unique():
    try:
        stock_obj = finvizfinance(ticker)
        stock_obj.ticker_charts(out_dir=str(output_dir))
        plot_volume_profile(ticker)
        plot_volume_profile_10y_5y(ticker)

        candidate_paths = [
            output_dir / f'{ticker}.jpg',
            output_dir / f'{ticker}.jpeg',
            Path(f'{ticker}.jpg'),
            Path(f'{ticker}.jpeg'),
        ]
        image_path = next((p for p in candidate_paths if p.exists()), None)

        if image_path is not None:
            display(Image(filename=str(image_path)))
        else:
            failed_chart_tickers.append(ticker)
    except Exception:
        failed_chart_tickers.append(ticker)

if failed_chart_tickers:
    print('Chart image not available for:')
    print(failed_chart_tickers)

Chart image not available for:
['NFLX', 'AZO', 'SOFI', 'VRSK', 'ROKU', 'EL.PA', 'MDB', 'TWLO', 'CTSH', 'VTRS', 'WDC', 'CCL', 'DECK', 'LOW', 'PAYC', 'NRG', 'SE', 'U', 'RDDT', 'XYZ', 'BSX', 'DELL', 'APA', 'IBM', 'ES', 'LVS', 'UBER', 'BE', 'EW', 'BUD', 'NKE', 'ADBE', 'ILMN', 'HUBS', 'TTWO', 'AES', 'VST', 'BABA', 'STM', 'ROL', 'NOW', 'LULU', 'RKLB', 'ORCL', 'STZ', 'MCD', 'BALL', 'GNRC', 'ACN', 'CLX', 'CPRT', 'TMUS', 'INTU', 'SWK', 'STX', 'EL', 'CASY', 'PYPL', 'NVO', 'LEN', 'GME', 'ZS', 'PFE', 'TSCO', 'BRO', 'IT', 'GPN', 'BKNG', 'BMNR', 'FICO']

### HMM Model

In [ ]:
# !pip install hmmlearn

In [ ]:
import numpy as np
from hmmlearn import hmm

In [ ]:
def fit_hmm_and_plot(ticker, data, n_components=3, n_iter=1000):
    """
    Fit a Gaussian HMM to a single ticker's OHLCV data and plot the close price
    coloured by the predicted hidden state.
    States are ranked by their mean log-return so colour is consistent:
        lowest mean return  â†’ red
        middle              â†’ orange
        highest mean return â†’ green
    """
    # --- data extraction ---
    try:
        df_stock = data[ticker].dropna()
    except KeyError:
        print(f"[SKIP] {ticker} not found in data.")
        return

    if len(df_stock) < 50:
        print(f"[SKIP] {ticker}: only {len(df_stock)} rows, need â‰¥ 50.")
        return

    # --- feature engineering ---
    log_returns = np.log(df_stock['Close'] / df_stock['Close'].shift(1))
    price_range = df_stock['High'] - df_stock['Low']

    features = pd.concat([log_returns, price_range], axis=1).dropna()
    features.columns = ['returns', 'range']

    # --- model fit ---
    model = hmm.GaussianHMM(
        n_components=n_components,
        covariance_type='full',
        n_iter=n_iter,
        # random_state=42,
    )
    try:
        model.fit(features)
    except Exception as e:
        print(f"[ERROR] HMM fit failed for {ticker}: {e}")
        return

    # --- state prediction ---
    states = pd.Series(model.predict(features), index=features.index, name='state')

    # rank states by mean return so colour assignment is stable across tickers
    state_mean_ret = {s: features.loc[states == s, 'returns'].mean() for s in range(n_components)}
    sorted_states = sorted(state_mean_ret, key=state_mean_ret.get)  # ascending
    palette = ['red', 'orange', 'green', 'blue', 'purple']          # worst â†’ best
    color_map = {state: palette[i] for i, state in enumerate(sorted_states)}

    # --- plot ---
    close = df_stock['Close'].loc[features.index]

    fig = go.Figure()
    for state in range(n_components):
        mask = states == state
        avg_pct = state_mean_ret[state] * 100
        fig.add_trace(go.Scatter(
            x=close[mask].index,
            y=close[mask],
            mode='markers',
            marker=dict(color=color_map[state], size=4),
            name=f'State {state}  (avg ret {avg_pct:+.3f}%)',
        ))

    fig.update_layout(
        title=f'HMM Hidden States “{ticker}”',
        xaxis_title='Date',
        yaxis_title='Close Price',
        height=500,
        legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
    )
    fig.show()

In [ ]:
# Run HMM for every ticker in the data-backed ticker list — one plot per ticker
failed_hmm = []

for ticker in getattr(data, 'tickers', final_symbols):
    try:
        fit_hmm_and_plot(ticker, data, n_components=3, n_iter=1000)
    except Exception as e:
        failed_hmm.append(ticker)
        print(f"[ERROR] {ticker}: {e}")

if failed_hmm:
    print("\\nFailed tickers (HMM):")
    print(failed_hmm)
else:
    print("HMM completed for all tickers.")

NameError: name 'data' is not defined

In [ ]:
# (single-ticker draft replaced by fit_hmm_and_plot â€” see cells above)

In [ ]:
# (single-ticker plot draft replaced by fit_hmm_and_plot â€” see cells above)

In [ ]:
# To improve the performance, you can try initializing it with customized transition probabilities and covariance matrices tailored to the features we use.

# You can also experiment with different emission probabilities, including Poisson distribution assumptions and custom models.

In [ ]:
# end of notebook